name: unistay
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"   # Flutter 3.24 serisi ile uyumlu

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0   # opsiyonel
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  geocoding: ^2.1.1
  table_calendar: ^3.0.9
  http: ^1.1.0

  # Routing (main.dart ve LoginPage'te kullanılıyor)
  go_router: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
