name: unistay
description: "A new Flutter project."
publish_to: 'none'
version: 1.4.0+7

environment:
  sdk: ">=3.4.0 <4.0.0"   # Flutter 3.24 serisi ile uyumlu

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.11.0
  nominatim_flutter: ^0.0.8 # Replace with the latest version

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0  
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image: ^4.1.3
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  geocoding: ^2.1.1
  table_calendar: ^3.0.9
  http: ^1.1.0
  url_launcher: ^6.2.2
  provider: ^6.0.0
  flutter_image_compress: ^2.0.4

  # Routing (main.dart ve LoginPage'te kullanılıyor)
  go_router: ^16.2.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.21.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/unistay_logo.png"
  android_icon_background_color: "#ffffff"
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/icon/unistay_logo.png"
    background_color: "#ffffff"
    theme_color: "#000000"

  windows:
    generate: true
    image_path: "assets/icon/unistay_logo.png"
    icon_size: 48

flutter:
  uses-material-design: true
  assets:
    - assets/ss2_unistay_price.tflite
    - assets/PointExploitation.csv
    - assets/synthetic_valais_price.csv
