// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXu9fFBcSQsePCg6Z15FI8RnA92LQ12Us',
    appId: '1:596123943594:web:7aac9bd4b98d9d9ce106d3',
    messagingSenderId: '596123943594',
    projectId: 'fir-flutter-codelab-82fe0',
    authDomain: 'fir-flutter-codelab-82fe0.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-82fe0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAhULAbk_xph7RkAF-siFcRvOA3239M2k',
    appId: '1:596123943594:android:f91f9286f0633554e106d3',
    messagingSenderId: '596123943594',
    projectId: 'fir-flutter-codelab-82fe0',
    storageBucket: 'fir-flutter-codelab-82fe0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ThxHu7LjRNl4rY9uGlBbGVF4K0jCNUs',
    appId: '1:596123943594:ios:dfeb18ec84fa4189e106d3',
    messagingSenderId: '596123943594',
    projectId: 'fir-flutter-codelab-82fe0',
    storageBucket: 'fir-flutter-codelab-82fe0.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ThxHu7LjRNl4rY9uGlBbGVF4K0jCNUs',
    appId: '1:596123943594:ios:dfeb18ec84fa4189e106d3',
    messagingSenderId: '596123943594',
    projectId: 'fir-flutter-codelab-82fe0',
    storageBucket: 'fir-flutter-codelab-82fe0.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
